// //types
// import { Product } from "../types/product.types";

// export const products: Product[] = [
//   {
//     id: 1,
//     name: "Teléfono móvil Samsung Galaxy S21",
//     price: 750,
//     condition: "Usado",
//     description: "Teléfono en buen estado con garantía de 3 meses.",
//     city: "Santa Cruz",
//     image: "1.jpg",
//     category: "Electrónica",
//     views: 105,
//     user: "Carlos Martínez",
//   },
//   {
//     id: 2,
//     name: "Sofá de tres plazas",
//     price: 300,
//     condition: "Usado",
//     description: "Sofá cómodo y amplio, ideal para el salón.",
//     city: "Cochabamba",
//     image: "2.jpg",
//     category: "Hogar",
//     views: 45,
//     user: "Ana Gómez",
//   },
//   {
//     id: 3,
//     name: "Bicicleta de montaña Trek",
//     price: 500,
//     condition: "Nuevo",
//     description: "Bicicleta perfecta para rutas y terrenos difíciles.",
//     city: "Santa Cruz",
//     image: "3.jpg",
//     category: "Deportes",
//     views: 88,
//     user: "Luis Fernández",
//   },
//   {
//     id: 4,
//     name: "Laptop Dell Inspiron",
//     price: 850,
//     condition: "Usado",
//     description: "Laptop en excelente estado, ideal para estudiantes.",
//     city: "Cochabamba",
//     image: "4.jpg",
//     category: "Electrónica",
//     views: 64,
//     user: "Carlos Martínez",
//   },
//   {
//     id: 5,
//     name: "Cámara Canon EOS 250D",
//     price: 1200,
//     condition: "Nuevo",
//     description: "Cámara DSLR con lente de 18-55mm.",
//     city: "Santa Cruz",
//     image: "5.jpg",
//     category: "Fotografía",
//     views: 72,
//     user: "Lucía Torres",
//   },
//   {
//     id: 6,
//     name: "Cama matrimonial con colchón",
//     price: 400,
//     condition: "Usado",
//     description: "Cama cómoda, incluye colchón ortopédico.",
//     city: "Cochabamba",
//     image: "6.jpg",
//     category: "Hogar",
//     views: 39,
//     user: "Luis Fernández",
//   },
//   {
//     id: 7,
//     name: "Reloj inteligente Apple Watch",
//     price: 500,
//     condition: "Usado",
//     description: "Reloj inteligente serie 6, en buen estado.",
//     city: "Santa Cruz",
//     image: "7.jpg",
//     category: "Electrónica",
//     views: 55,
//     user: "Ana Gómez",
//   },
//   {
//     id: 8,
//     name: "Zapatos deportivos Nike Air",
//     price: 120,
//     condition: "Nuevo",
//     description: "Zapatos ideales para correr y caminar.",
//     city: "La Paz",
//     image: "8.jpg",
//     category: "Moda",
//     views: 77,
//     user: "David Sánchez",
//   },
//   {
//     id: 9,
//     name: "Libro 'Cien años de soledad'",
//     price: 15,
//     condition: "Usado",
//     description: "Edición de bolsillo, perfecto estado.",
//     city: "Tarija",
//     image: "9.jpg",
//     category: "Libros",
//     views: 34,
//     user: "Lucía Torres",
//   },
//   {
//     id: 10,
//     name: "Guitarra acústica Yamaha",
//     price: 220,
//     condition: "Usado",
//     description: "Guitarra con cuerdas nuevas y funda incluida.",
//     city: "Santa Cruz",
//     image: "10.jpg",
//     category: "Música",
//     views: 50,
//     user: "David Sánchez",
//   },
//   {
//     id: 11,
//     name: "Bocina Bluetooth JBL",
//     price: 100,
//     condition: "Nuevo",
//     description:
//       "Bocina resistente al agua, ideal para actividades al aire libre.",
//     city: "Santa Cruz",
//     image: "11.jpg",
//     category: "Electrónica",
//     views: 65,
//     user: "Isabel Martínez",
//   },
//   {
//     id: 12,
//     name: "Chaqueta de cuero",
//     price: 150,
//     condition: "Usado",
//     description: "Chaqueta de cuero en excelente estado, talla M.",
//     city: "La Paz",
//     image: "12.jpg",
//     category: "Moda",
//     views: 80,
//     user: "Carlos Martínez",
//   },
//   {
//     id: 13,
//     name: "Silla ergonómica",
//     price: 200,
//     condition: "Nuevo",
//     description: "Silla cómoda para oficina, ajustable y con soporte lumbar.",
//     city: "La Paz",
//     image: "13.jpg",
//     category: "Hogar",
//     views: 60,
//     user: "Juan Pérez",
//   },
//   {
//     id: 14,
//     name: "Taza personalizada",
//     price: 10,
//     condition: "Nuevo",
//     description: "Taza de cerámica personalizada con nombre.",
//     city: "Santa Cruz",
//     image: "14.jpg",
//     category: "Regalos",
//     views: 25,
//     user: "Isabel Martínez",
//   },
//   {
//     id: 15,
//     name: "Cámara GoPro Hero 9",
//     price: 300,
//     condition: "Nuevo",
//     description: "Cámara deportiva, resistente al agua y con estabilización.",
//     city: "Santa Cruz",
//     image: "15.jpg",
//     category: "Electrónica",
//     views: 40,
//     user: "Juan Pérez",
//   },
// ];
